#!/usr/local/bin/python

import os
import json

# install packages
# amplitudejs had to be installed this way 
# bc its code from website has some weird bug
print('installing packages..')

os.system('npm install')
os.system('mv amplitudejs node_modules')

# detach this repo from mine and link to yours instead
print('re-linking repo..')

with open ('package.json') as f:
    data = json.load(f)
username = data['github_username']
site_repo = os.path.basename(data['homepage'])
repo = 'https://github.com/' + username + '/' + site_repo + '.git'
os.system('git remote set-url --push origin ' + repo)

print('done!')
