#!/usr/local/bin/python

import sys
import os

argc = len(sys.argv)
scripts_dir = os.environ['MRBLOG_SCRIPTS']

if argc==1:
    print('-------- Welcome to mrblog! --------')
    print('Currently configured for domain: '+os.environ['MRBLOG_DOMAIN'])
    with open(scripts_dir + '/usage', 'r') as file:
        print file.read()

elif sys.argv[1]=='new':
    os.system(scripts_dir + '/new')
elif sys.argv[1]=='publish':
    os.system(scripts_dir + '/publish')
elif sys.argv[1]=='pic':
    if argc>=3:
        os.system(scripts_dir + '/post_pic ' + sys.argv[2])
    else:
        print('give another argument (image path)')