#!/usr/bin/env python3

import glob
import os

content_dir = os.environ['MRBLOG_CONTENT']
paths = glob.glob(content_dir + '/pics/*.jpg')
morepaths = glob.glob(content_dir + '/pics/*.png')
paths.extend(morepaths)
for path in paths:
    info = os.popen('magick identify -format "%w %h" '+path).read()
    wh = info.split(' ')
    w = int(wh[0])
    h = int(wh[1])
    if (w>800 or h>640):
        cmd='magick "'+path+'" -resize "800x640>" -quality 100 "'+path+'"'
        os.system(cmd)

print('resized large images')
