#!/usr/local/bin/python

import sys
import os

if os.path.isdir('node_modules/amplitudejs'):
    os.system('mv node_modules/amplitudejs .')
os.system('rm -rf node_modules')

print('done uninstalling')