#!/usr/bin/env bash

git fetch upstream master
git checkout FETCH_HEAD scripts
git checkout FETCH_HEAD public
git checkout FETCH_HEAD .env
git checkout FETCH_HEAD src/index.js

echo "updated to match original repo"
